// Generated by CoffeeScript 1.8.0
(function() {
  exports.pack = function(data, cb) {

    var s = '', packed = '';

    // Transform into binary string
    for (var i = 0; i < data.length; i++) {
      if(data[i] === true){
          s += '1';
        } else {
          s += '0';
        }
      }

    // Break in chunks of 8 chars to represent a binary number
    // convert binary number into int(base 10) and convert to String Char
    // add String char togther to form compressed data
    var start = 0, end = 8;
    while(end <= s.length){
      var sub = s.substring(start, end);
      packed += String.fromCharCode(parseInt(Number(sub), 2));
      start += 8;
      end += 8;
    }
    return cb(null, packed);
  };



  exports.unpack = function(buffer, cb) {

    // Add leading zeros to binary numbers
    function padding(num, size) {
      var pad = "00000000" + num;
      return pad.substr(pad.length-size);
    }

    var data = [];
    var s = '';

    // Transform Sting chars into binary numbers
    for(var i = 0; i < buffer.length; i ++){
      var num = buffer.charCodeAt(i);
      s += padding(num.toString(2), 8);
    }

    // Convert 1 and 0 to true and false to represent intial data Array
    for (var i = 0; i < s.length; i++) {
      var sub = s.substring(i, i+1);

      if(sub === '1'){
        data.push(true);
      } else {
        data.push(false);
      }
    }

    return cb(null, data);
  };

}).call(this);
