// Generated by CoffeeScript 1.8.0
(function() {
  exports.pack = function(data, cb) {

    var s = '', packed = '';

    // Transform into binary string
    for (var i = 0; i < data.length; i++) {
      if(data[i] === true){
          s += '1';
        } else {
          s += '0';
        }
      }

    var start = 0, end = 8;
    while(end <= s.length){
      var sub = s.substring(start, end);
      packed += String.fromCharCode(parseInt(Number(sub), 2));
      start += 8;
      end += 8;
    }
    return cb(null, packed);
  };



  exports.unpack = function(buffer, cb) {

    function padding(num, size) {
      var pad = "00000000" + num;
      return pad.substr(pad.length-size);
    }

    var data = [];
    var s = '';

    for(var i = 0; i < buffer.length; i ++){
      var num = buffer.charCodeAt(i);
      s += padding(num.toString(2), 8);
    }

    for (var i = 0; i < s.length; i++) {
      var sub = s.substring(i, i+1);

      if(sub === '1'){
        data.push(true);
      } else {
        data.push(false);
      }
    }

    return cb(null, data);
  };

}).call(this);
